e2e: fix spec parameter in run.sh

diff --git a/ci/Dockerfile.assets.server b/ci/Dockerfile.assets.server
--- a/ci/Dockerfile.assets.server
+++ b/ci/Dockerfile.assets.server
@@ -1,5 +1,34 @@
+# Here is a description of how this image is built. We use the Juno-Base image, which 
+# includes all the necessary scripts and caches the node_modules (for performance reasons). 
+# Additionally, we use the (modified by us) Cypress image to run mount tests. 
+# Finally, we build the final Assets Server Image from the Nginx image.
+#
+# First, we fetch the Base Image (Build Layer) and copy the context to /tmp/latests. 
+# In this case, the context is provided by the pipeline and consists of the built assets,
+# Juno Apps, libs, and 3rd Party Apps.
+#
+# In the second step, based on these assets and their dependencies, we generate the Importmap 
+# and Manifest along with the converted external packages.
+#
+# Next, in the second Build Layer, we fetch the Cypress Image and copy the results from the first 
+# layer (apps, libs, externals, importmap.json, manifest.json) to /tmp/latest. Furthermore, 
+# we copy the e2e directory from Base to /tmp/e2e.
+#
+# The idea is to simulate the final server using the serve npm package. Therefore, in this step, 
+# we need to create the mount-test.html file and install serve. To execute the Cypress Test during 
+# the build, we need to start serve and cypress in a single RUN Layer. We run the mount test for 
+# each asset from the context. If the test is positive, it is included in the passed apps. 
+# Otherwise, we ignore it. We keep track of this in the assetsBuildLog file, which we later 
+# use in the manifest.
+#
+# Finally, we build the final Server Image and only use the assets that have passed the tests.
+
 ARG BASE_URL_PLACEHOLDER="%BASE_URL%"
 ARG EXIT_ON_ERROR="true"
+ARG VERBOSE="false"
+
+# Cypress image
+FROM keppel.eu-de-1.cloud.sap/ccloud/cypress-client:latest AS cypress
 
 # Latest assets server image
 # FIRSTRUN!
@@ -10,9 +39,9 @@ ARG EXIT_ON_ERROR="true"
 FROM keppel.eu-de-1.cloud.sap/ccloud/juno-v3-assets-server:latest AS lastbuild
 
 # Base image
+########################### BASE ################################
 FROM keppel.eu-de-1.cloud.sap/ccloud/juno-v3-base:latest AS base 
-ARG BASE_URL_PLACEHOLDER
-
+# Create a directory for the latest assets
 RUN mkdir -p /tmp/latest
 
 # copy all app and lib builds (from dist) to tmp/latest  
@@ -22,21 +51,110 @@ RUN mkdir -p /tmp/latest
 # -> /apps/volta/build, package.json
 # -> /libs/juno-ui-components/build, package.json
 ADD . /tmp/latest
-WORKDIR /tmp/latest
 
-ARG NPM_PROVIDER="jspm"
+# set the working directory to /tmp/latest
+WORKDIR /tmp/latest
+######################## END BASE ###############################
+
+
+####################### TEST FILES ############################
+FROM base AS test-importmap
+ARG EXIT_ON_ERROR="false"
 ARG VERBOSE="false"
+ARG BASE_URL_PLACEHOLDE="http://localhost:3000"
+
+# Generate importmap and manifest only for latest apps and libs
+# this step also generates the externals esm packages
+RUN \
+  set -e ; \
+  node /juno/ci/scripts/esm_build/generate_importmap.mjs \
+  --node-modules-path=/tmp/ \
+  --external-path=externals \
+  --exit-on-error=$EXIT_ON_ERROR \
+  --src=./ \
+  --base-url=$BASE_URL_PLACEHOLDE \
+  --ignore-externals=false \
+  --output=./importmap.json  \
+  --verbose=$VERBOSE ; \
+  \
+  node /juno/ci/scripts/generate_manifest.mjs \
+  --src=./ \
+  --output=./manifest.json \
+  --base-url=$BASE_URL_PLACEHOLDER \
+  --verbose=$VERBOSE ;
+###################### END IMPORTMAP MANIFEST EXTERNALS ############################
+
+
+###################### CYPRESS CLIENT ############################
+FROM cypress AS cypress-client 
+# copy the e2e directory from the base image to /tmp/e2e
+COPY --from=base /juno/e2e /tmp/e2e
+# copy the latest assets from the base image to /tmp/latest
+COPY --from=test-importmap /tmp/latest /tmp/latest
+# copy mount-test.html from the base image to /tmp/latest
+COPY --from=base /juno/ci/assets-server/mount-test.html /tmp/latest/mount-test.html
+
+# set the working directory to /tmp/e2e
+WORKDIR /tmp/latest 
+
+# install serve and jq
+RUN apt-get update && apt-get install -y jq ; npm i -g serve   
+
+# create a serve config file, create a directory for the passed assets and run 
+# the mount test for each asset
+
+RUN mkdir -p /tmp/passed /tmp/build ; \
+  echo '[]' > /tmp/build/log.json ; \
+  echo '{"cleanUrls": false}' > /tmp/serve.config.json ; \
+  echo "=== RUN MOUNT TESTS ===\n" ; \
+  serve -c /tmp/serve.config.json & sleep 5 ; \
+  cd /tmp/e2e/ ; \
+  for f in /tmp/latest/**/*/package.json; do \
+  NAME=$(cat $f | jq -r '.name') ; \
+  VERSION=$(cat $f | jq -r '.version') ; \
+  echo "$NAME@$VERSION" ; \
+  mkdir -p "/tmp/build/$NAME@$VERSION" ; \
+  TYPE_FOLDER=$(basename $(dirname $(dirname $f))) ; \
+  cypress-cloud --record false -s "cypress/integration/assets-server/mount_asset.spec.js" \
+  --ci-build-id "$(date) - MOUNT CI - assets-qa-tests - chrome" \
+  --browser chrome \
+  --env APP_NAME=$NAME,APP_VERSION=$VERSION \
+  --config baseUrl="http://localhost:3000" , screenshotsFolder="/tmp/build/$NAME@$VERSION" ; \ 
+  # Check the exit status of the cp command \
+  if [ $? -eq 0 ]; then \
+  cp -r $(dirname $f) /tmp/passed/$TYPE_FOLDER/ && \ 
+  STATUS="passed" ; \
+  else \
+  STATUS="failed" ; \
+  fi ; \
+  echo "$NAME@$VERSION $STATUS" && \
+  jq --arg n "$NAME" --arg v "$VERSION" --arg s "$STATUS" --arg l "/build-log/$NAME@$VERSION" \
+  '. += [{"name": $n, "version": $v, "status": $s, "log": $l}]' /tmp/build/log.json > /tmp/build/log.json.temp && \
+  mv /tmp/build/log.json.temp /tmp/build/log.json ; \
+  done
+
+###################### END CYPRESS CLIENT ############################
+
+####################### FINAL FILES ############################
+FROM base AS final-files
+ARG EXIT_ON_ERROR="true"
+ARG VERBOSE="false"
+ARG BASE_URL_PLACEHOLDER
 
 # create folder in tmp for merged assets
 RUN mkdir -p /tmp/final 
-
 # copy old versions of assets to current layer
 # FIRSTRUN!
 # NOTE: if this image does not exist 
 #       this is the case if the image was not build before
 #       comment out this line for the first run
 COPY --from=lastbuild /usr/share/nginx/html /tmp/final
+# copy passed assets from the cypress-client to /tmp/passed
+COPY --from=cypress-client /tmp/passed /tmp/passed
+COPY --from=cypress-client /tmp/build /tmp/build
+WORKDIR /tmp/passed
 
+RUN pwd
 # delete old assets. Use it once to clean up the old assets.
 # RUN rm -rf /tmp/final/externals/*
 
@@ -69,6 +187,8 @@ RUN \
   rm -rf externals_* importmap* importmap* ; \
   node /juno/ci/scripts/delete_obsolete_assets.js --manifest=/juno/ci/obsolete_assets.json --src=./
 
+RUN rm -rf externals/npm:*
+
 # Create importmaps and manifest
 RUN \
   set -e ; \
@@ -86,8 +206,11 @@ RUN \
   --src=./ \
   --output=./manifest.json \
   --base-url=$BASE_URL_PLACEHOLDER \
+  --assets-build-log=/tmp/build/log.json \
   --verbose=$VERBOSE ;
 
+
+RUN ls -la externals ; pwd ; head -20 manifest.json ; head -20 importmap.json
 # RESULTS
 # /tmp/final/apps/whois@version/files
 # /tmp/final/apps/volta/files
@@ -101,115 +224,40 @@ RUN \
 RUN chmod +x /juno/ci/scripts/check_file_integrity.sh && \
   /juno/ci/scripts/check_file_integrity.sh global apps libs assets externals index.html mount-test.html manifest.json importmap.json
 
-# create self signed dummy certificate and key
-RUN apk add openssl ; openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
-  -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=dummy" \
-  -keyout /tmp/tls.key  -out /tmp/tls.crt
+# # create self signed dummy certificate and key
+# RUN apk add openssl ; openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
+#   -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=dummy" \
+#   -keyout /tmp/tls.key  -out /tmp/tls.crt
 
-############### FINAL IMAGE! ###################
+############### END FINAL IMPORTMAP ############################
+
+############### FINAL SERVER IMAGE ############################
 FROM keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/library/nginx:alpine AS server
 ARG BASE_URL_PLACEHOLDER
 
 LABEL source_repository="https://github.com/sapcc/juno"
 
 # delete default html files of nginx
-RUN rm -rf /usr/share/nginx/html ; 
+RUN rm -rf /usr/share/nginx/html 
 # copy tls certificate and key
-COPY --from=base /tmp/tls.crt /tmp/tls.key /etc/ssl/juno/ 
-# COPY --from=base /tmp/tls.key /etc/ssl/sap/tls.key
+# COPY --from=base /tmp/tls.crt /tmp/tls.key /etc/ssl/juno/ 
+# create self signed dummy certificate and key
+RUN mkdir -p /etc/ssl/juno ; apk add openssl ; openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
+  -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=dummy" \
+  -keyout /etc/ssl/juno/tls.key  -out /etc/ssl/juno/tls.crt
 
-# copy new version 
-COPY --from=base /tmp/final "/usr/share/nginx/html"
 
-# Replace default nginx config
-RUN rm -rf /etc/nginx/conf.d/default.conf && echo -e $'\
-  server { \n \
-  \troot  /usr/share/nginx/html; \n\
-  \tadd_header Access-Control-Allow-Origin *;\n\
-  \tlisten       80; \n \
-  \tlisten 443 default_server ssl; \n\ 
-  \tssl_certificate     /etc/ssl/juno/tls.crt; \n\
-  \tssl_certificate_key /etc/ssl/juno/tls.key; \n\
-  \tserver_name  localhost; \n \
-  \tinclude mime.types; \n \
-  \ttypes \n \ 
-  \t{ \n \
-  \t\tapplication/javascript mjs js; \n \
-  \t} \n \
-  \n \
-  \tlocation / { \n \
-  \t\tindex  index.html index.htm; \n \
-  \t} \n \
-  \n \
-  \tlocation ~* (importmap|manifest).*\.json$ { \n \
-  \t\tsub_filter '$BASE_URL_PLACEHOLDER$' "https://$host"; \n \
-  \t\tsub_filter_types *; \n \
-  \t\tsub_filter_once off; \n \
-  \t\tadd_header Cache-Control "no-store, no-cache"; \n \
-  \t\tadd_header Access-Control-Allow-Origin *;\n\
-  \t} \n \
-  \n \
-  \tlocation ~* .*widget-loader@latest.*\.js$ { \n \
-  \t\tadd_header Cache-Control "no-store, no-cache"; \n \
-  \t\tadd_header Access-Control-Allow-Origin *;\n\
-  \t}\n \
-  } \n \
-  ' > /etc/nginx/conf.d/default.conf
+# copy from final-importmap generated files, importmap.json, manifest.json, externals and assets
+COPY --from=final-files /tmp/final /usr/share/nginx/html
+# copy from cypress-client generated files, passed and build
+COPY --from=cypress-client /tmp/build /usr/share/nginx/html/build-log
+# copy index.html from base image to /usr/share/nginx/html
+COPY --from=base /juno/ci/assets-server/index.html /usr/share/nginx/html/index.html
+# copy nginx config from base image to /etc/nginx/conf.d/default.conf
+COPY --from=base /juno/ci/assets-server/nginx.config /etc/nginx/conf.d/default.conf
+# replace base url placeholder in nginx config with actual base url placeholder
+RUN sed -i -e "s/__BASE_URL_PLACEHOLDER__/${BASE_URL_PLACEHOLDER}/g" /etc/nginx/conf.d/default.conf
 
-# Create the index.html with the assets-overview micro frontend app
-RUN echo -e $'\
-  <!DOCTYPE html> \n\
-  <html style="height: 100vh; background: rgb(13, 20, 28);">\n\
-  \t<head>\n\
-  \t\t<title>Juno Assets</title> \n \
-  \t\t<link rel="icon" href="/assets/favicon.ico"/> \n\
-  \t</head>\n\
-  \t<body style="height: 100vh;">\n \
-  \t\t<script \n\
-  \t\t\tsrc="/apps/widget-loader@latest/build/app.js" \n\ 
-  \t\t\tdata-name="assets-overview" \n\
-  \t\t\tdata-props-manifest-url="/manifest.json"></script>\n\
-  \t</body>\n\
-  </html>' > /usr/share/nginx/html/index.html   
-
-RUN echo -e $'\
-  <!DOCTYPE html> \n\
-  <html lang="en"> \n\
-  \t<head> \n\
-  \t\t<meta charset="UTF-8" /> \n\
-  \t\t<title>Assets Test</title> \n\
-  \t\t<style> \n\
-  \t\t\t.blured { \n\
-  \t\t\t\tposition: absolute; \n\
-  \t\t\t\tleft: 0; \n\
-  \t\t\t\tright: 0; \n\
-  \t\t\t\ttop: 0; \n\
-  \t\t\t\tbottom: 0; \n\
-  \t\t\t\tbackdrop-filter: blur(10px); \n\
-  \t\t\t\tz-index: 1000; \n\
-  \t\t\t} \n\
-  \t\t</style> \n\
-  \t</head> \n\
-  \t<body> \n\
-  \t\tAsset mount test \n\
-  \t\t<script> \n\
-  \t\t\tconst params = new URLSearchParams(window.location.search) \n\
-  \t\t\tconst { name, version, props } = JSON.parse(atob(params.get("config"))) \n\
-  \t\t\tconst script = document.createElement("script") \n\
-  \t\t\tscript.src = "/apps/widget-loader@latest/build/app.js" \n\
-  \t\t\tscript.setAttribute("data-name", name) \n\
-  \t\t\tscript.setAttribute("data-version", version) \n\
-  \t\t\tif (props) { \n\
-  \t\t\t\tObject.keys(props).forEach((key) => { \n\
-  \t\t\t\t\tconst propKey = key.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase()) \n\
-  \t\t\t\t\tscript.setAttribute(`data-props-${propKey}`, props[key]) \n\
-  \t\t\t\t}) \n\
-  \t\t\t} \n\
-  \t\t\tdocument.currentScript.replaceWith(script) \n\
-  \t\t</script> \n\
-  \t\t<div class="blured"></div> \n\
-  \t</body> \n\
-  </html>' > /usr/share/nginx/html/mount-test.html   
-
+WORKDIR /usr/share/nginx/html
 # default command is nginx
 # CMD nginx -g "daemon off;"
