fix combine assets step

diff --git a/ci/pipeline.yaml.erb b/ci/pipeline.yaml.erb
--- a/ci/pipeline.yaml.erb
+++ b/ci/pipeline.yaml.erb
@@ -428,17 +428,21 @@ jobs:
                 # compose everthing together that we can use it in the asset-server image build
                 <% ASSETS_SOURCE.each do |name,asset_types|%>
                   <% asset_types.each do |asset_type|%>
-                    # check and compose everthing in the dist output folder that
-                    # we can combine everything in the asset-server buid step
-                    if [[ "<%= name %>" == "juno-3rd-party" ]]; then
-                      # if the integrity check for 3rd party fails there will be no error
-                      # because we do not want a blocked pipeline
-                      # but an error log is uploaded to the 3rd party apps/libs folder
-                      # if an error_log was found the new version is not deployed
-                      ./ci/scripts/compose_assets.sh --error-on-exit 0 --asset-type <%= asset_type %> --source-path ../  --dist-path $DIST_PATH --kind <%= name %>
-                    else
-                      ./ci/scripts/compose_assets.sh --error-on-exit 1 --asset-type <%= asset_type %> --source-path ../  --dist-path $DIST_PATH --kind <%= name %>
-                    fi
+                <% 
+                # check and compose everthing in the dist output folder that
+                # we can combine everything in the asset-server build step
+                %>
+                    <% if name.to_s == "juno-3rd-party" %>
+                <%
+                # if the integrity check for 3rd party fails there will be no error
+                # because we do not want a blocked pipeline
+                # but an error log is uploaded to the 3rd party apps/libs folder
+                # if an error_log was found the new version is not deployed
+                %>
+                ./ci/scripts/compose_assets.sh --error-on-exit 0 --asset-type <%= asset_type %> --source-path ../  --dist-path $DIST_PATH --kind <%= name %>
+                    <% else %>
+                ./ci/scripts/compose_assets.sh --error-on-exit 1 --asset-type <%= asset_type %> --source-path ../  --dist-path $DIST_PATH --kind <%= name %>
+                    <% end %>
                   <% end %>
                 <% end %>
                 echo ""
