deactivate blocker

diff --git a/.github/workflows/block-deprecated_assets.yml b/.github/workflows/block-deprecated_assets.yml
--- a/.github/workflows/block-deprecated_assets.yml
+++ b/.github/workflows/block-deprecated_assets.yml
@@ -24,7 +24,7 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           repository: ${{ github.event.pull_request.head.repo.full_name }}
           ref: ${{ github.event.pull_request.head.ref }}
-      
+
       - uses: dorny/paths-filter@v3
         id: filters
         with:
@@ -32,7 +32,7 @@ jobs:
           filters: |
             apps: apps_deprecated/**
             libs: libs_deprecated/**
-    
+
       - name: Show outputs
         run: |
           echo "===================="
@@ -54,9 +54,8 @@ jobs:
           echo app changes: ${{ needs.changes.outputs.app-changes }}
           echo lib changes: ${{ needs.changes.outputs.lib-changes }}
 
-      - name: Check if changes belong to deprecated apps or libs
-        if: ${{ needs.changes.outputs.apps == 'true' || needs.changes.outputs.libs == 'true' }}
-        run: |
-          echo "::error not allowed to make changes to deprecated apps or libs"
-          exit 1
-        
+      # - name: Check if changes belong to deprecated apps or libs
+      #   if: ${{ needs.changes.outputs.apps == 'true' || needs.changes.outputs.libs == 'true' }}
+      #   run: |
+      #     echo "::error not allowed to make changes to deprecated apps or libs"
+      #     exit 1
