simplify the worflow since we are to allowd to make changes on deprecated libs and apps

diff --git a/.github/workflows/block-apps.yml b/.github/workflows/block-apps.yml
--- a/.github/workflows/block-apps.yml
+++ b/.github/workflows/block-apps.yml
@@ -24,16 +24,7 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           repository: ${{ github.event.pull_request.head.repo.full_name }}
           ref: ${{ github.event.pull_request.head.ref }}
-      - name: Generate app and lib filters
-        run: |
-          for folder in apps_deprecated/*; do
-            folder_name=$(basename "$folder")
-            echo "$folder_name: $folder/**" >> temp_app_filters.yaml
-          done
-          for folder in libs_deprecated/*; do
-            folder_name=$(basename "$folder")
-            echo "$folder_name: $folder/**" >> temp_lib_filters.yaml
-          done
+      
       - uses: dorny/paths-filter@v3
         id: filters
         with:
@@ -41,22 +32,9 @@ jobs:
           filters: |
             apps: apps_deprecated/**
             libs: libs_deprecated/**
-      - uses: dorny/paths-filter@v3
-        id: app-filters
-        with:
-          list-files: shell
-          filters: temp_app_filters.yaml
-      - uses: dorny/paths-filter@v3
-        id: lib-filters
-        with:
-          list-files: shell
-          filters: temp_lib_filters.yaml
+    
       - name: Show outputs
         run: |
-          echo "===================="
-          cat temp_app_filters.yaml
-          echo "===================="
-          cat temp_lib_filters.yaml
           echo "===================="
           echo apps: ${{ steps.filters.outputs.apps}}
           echo apps_files: ${{ steps.filters.outputs.apps_files}}
@@ -68,9 +46,6 @@ jobs:
   evaluate-changes:
     needs: changes
     runs-on: [ubuntu-latest]
-    env:
-      APPS: "supernova heureka greenhouse greenhouse-management exampleapp template"
-      LIBS: "communicator oauth policy-engine messages-provider juno-ui-components url-state-provider url-state-router utils"
     steps:
       - name: Show inputs
         run: |
@@ -79,27 +54,9 @@ jobs:
           echo app changes: ${{ needs.changes.outputs.app-changes }}
           echo lib changes: ${{ needs.changes.outputs.lib-changes }}
 
-      # - name: Check if changes belong to restricted apps or libs
-      #   id: check-changes
-      #   run: |
-      #     check_changes() {
-      #       local changes=$1
-      #       local list=$2
-      #       local type=$3
-      #       for item in $list; do
-      #         if [[ $changes == *"$item"* ]]; then
-      #           echo "Not allowed to make changes to specified deprecated $type: $item"
-      #           exit 1
-      #         fi
-      #       done
-      #       echo "No restricted changes found in $type"
-      #       return 0
-      #     }
-
-      #     app_changes="${{ needs.changes.outputs.app-changes }}"
-      #     lib_changes="${{ needs.changes.outputs.lib-changes }}"
-
-      #     check_changes "$app_changes" "$APPS" "app"
-      #     check_changes "$lib_changes" "$LIBS" "lib"
-
-      #     echo "Changes are allowed."
+      - name: Check if changes belongs to apps supernova, huereka, greenhouse or greenhouse-management or libs communicator, oauth, policy-engine, messages-provider or juno-ui-components
+        if: |
+          ${{ needs.changes.outputs.apps }} == true || ${{ needs.changes.outputs.libs }} == true
+        run: |
+          echo "::error not allowed to make changes to deprecated apps or libs"
+          exit 1
