Update build&deploy.yml

diff --git a/.github/workflows/build&deploy.yml b/.github/workflows/build&deploy.yml
--- a/.github/workflows/build&deploy.yml
+++ b/.github/workflows/build&deploy.yml
@@ -51,7 +51,7 @@ jobs:
           scope: "@${{ github.repository_owner }}"
       - name: build libs
         run: |
-          echo "::warning title=WARNUNG::FDSFDSFDSFDSFDSFSDFSDFSDF"
+          
           ls -la
           echo "====apps"
           ls -la apps
@@ -83,6 +83,11 @@ jobs:
           
           # publish to https://github.com/${{ github.repository_owner }}/packages
           npm -w "@${REPOSITORY_OWNER}/${ASSET_SCOPE}${ASSET_NAME}" publish #--dry-run
+
+          if [ "$?" -gt 0 ]; then
+              echo "::warning title=WARNUNG::Could not publish to github. Maybe you forgot to increment the version?"
+              exit 1
+          fi
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REPOSITORY_OWNER: ${{ github.repository_owner }}
