Update build&deploy.yml

diff --git a/.github/workflows/build&deploy.yml b/.github/workflows/build&deploy.yml
--- a/.github/workflows/build&deploy.yml
+++ b/.github/workflows/build&deploy.yml
@@ -83,7 +83,9 @@ jobs:
           
           # publish to https://github.com/${{ github.repository_owner }}/packages
           npm -w "@${REPOSITORY_OWNER}/${ASSET_SCOPE}${ASSET_NAME}" publish #--dry-run
-          
+
+          echo $?
+          echo "::warning title=WARNUNG::Could not publish to github. Maybe you forgot to increment the version?"
           if [ $? != 0 ] ; then
             echo "::warning title=WARNUNG::Could not publish to github. Maybe you forgot to increment the version?"
           fi
